### ISSUE TITLE
Flow Cylinder Test Case 

### ISSUE THREAD

**Issue by SohailAusgur** [DualSPHysics/DualSPHysics#225]
Looking at the .xml file for the Flow Cylinder test case. It says the Reynolds Number is 200, however the inlet velocity is 1m/s with a width of 2m for the inlet. How is that possible? Using the parameters viscosity and density stated in the code, the Reynolds number turns out to be 1500000.

Can someone please clear this up. Maybe I am missing something.

**Comment by AhmedSalih3d** [comment]
Hello Sohail!

Seems like you resolved your issue, but for anyone else wondering it is because of the following. Reynolds number is defined as:

 $Re = \frac{u \cdot L}{\nu} $

Where is the flow velocity, L is a characteristic length and $\nu$ is the kinematic viscosity. In the `CaseFlowCylinder_Re200_Def.xml` the following is defined:

L (Diameter) = 0.2 m (2 x radius)
u                   = 1 m/s
$\nu$            = 0.001 m^2/s #This is not a typical value for water, but remember it can be some other fluid

Combining all of this:

$Re = \frac{1 \cdot 0.2}{0.001} = 200$

Hope this helps!

Kind regards

**Comment by SohailAusgur** [comment]
Thank you for the reply. It clears things up. 

Would you know if there needs to be any modifications to make in Ansys Fluent in order to achieve the exact same or very similar result as the one in DualSPHysics

**Comment by AhmedSalih3d** [comment]
> Thank you for the reply. It clears things up.
> 
> Would you know if there needs to be any modifications to make in Ansys Fluent in order to achieve the exact same or very similar result as the one in DualSPHysics

Awesome!

Yes, Ansys Fluent should be able to replicate this easily and better, since it can apply the correct no-slip condition on the surfaces of objects. I would trust the results of Ansys Fluent over DualSPHysics in this internal flow case, but as always better to compare with experiments.
