### ISSUE TITLE
Boundary Particles excluded in DEM contact

### ISSUE THREAD

**Issue by eleclizard** [DualSPHysics/DualSPHysics#44]
Hi,

I am exploring the DEM capability of DualSPHyisics and I tried to make some modification of one of the example of DualSPHysics v4.4: CaseManyFloatings. The modification is in the case definition xml file I changed the sphere materials into all steels. However, I soon found out that the solution is not stable and the following error popped up:
"*** ERROR: Some boundary particle was excluded. ***
TimeStep: 0.233614  (Nstep: 8201)
Total boundary: 12  (fixed=0  moving=0  floating=12)
Excluded for: position=0  rhop=0  velocity=12

*** Exception (JSphGpuSingle::AbortBoundOut)
Text: Fixed, moving or floating particles were excluded. Check VTK file Error_BoundaryOut.vtk with excluded particles."

Would anyone mind helping me with how I can modify the parameters so that the solution for this DEM interation is stable? I have attached the zip file with the case definition xml file, the material properties xml file, and the batch file that I used (may have to change location of DualSPHysics directory).

Thank you for your time!
[CaseManyFloatings.zip](https://github.com/DualSPHysics/DualSPHysics/files/4466188/CaseManyFloatings.zip)

**Comment by RBCanelas** [comment]
hi,

steel is a tricky one because it is very rigid. I would suggest you experiment a bit with lower rigidities and different restitution coeffs. This might not seem ideal, but neither is DEM, the chrono DVI implementation for contacts is effectively replacing it. Should be out very very soon, the team is giving the final touches to the beta release!

Cheers

**Comment by eleclizard** [comment]
hi,

Thank you for your reply! Just a little bit of curiosity, I actually had a read through your PhD thesis and in section 5.2.3 Normal Dry Colisions it says that the simulations of a ball hitting a wall with the same material uses steel with the coefficient of restitution of 0.85 and gives out result. Was this because gravity was not counted in those simulations and in my case I have the ball under the influence of gravity?

Thanks!

**Comment by LiangZhengyuCSU** [comment]
The modeling of rigid bodies requires very small time steps (since the contact forces are normally very large). In this example of many floatings, A lower bound of timestep is imposed on the simulation (this might be a wired setting for DEM users). After the program automatically revises your time step, your particle assembly will be very likely to "explode," and your particle velocity may exceed the velocity limit. This will trigger an error and halt the simulation.

**Comment by eleclizard** [comment]
Hi,

Thank you for the reply! Is there a way that I can forcefully lower down the timestep? I know that in DualSPHysics DEM there is a variable time step that is 1/50 of the contact duration but what if this is not enough?

Regards,

**Comment by jmdalonso** [comment]
Hi,

You can change the value of cflnumber in the section `<constantsdef>` of the XML file. it is also explained on the page 16 of the document XML_GUIDE_v5.0.pdf

Regards,
