### ISSUE TITLE
Potential Error with particle counting?

### ISSUE THREAD

**Issue by AhmedSalih3d** [DualSPHysics/DualSPHysics#62]
Hi

I may recall this incorrectly, but I believe in past versions when opening bi4 files and checking these values;

![image](https://user-images.githubusercontent.com/36305327/94304148-50c8a180-ff6f-11ea-9b91-ea9ea7968d31.png)

These values should reflect the actual number of particles in the simulation currently. In my case CaseNp = 64720, but if I go down and check at any Array:

![image](https://user-images.githubusercontent.com/36305327/94304259-866d8a80-ff6f-11ea-9a6e-657f6f332343.png)

I am using DualSPHysics v5.0. 

Is this a change or am I mistaken about it being different before? 

The reason I care about this, is that I am making a post-processing script using bi4 files, and to extract the correct particles I need the right range, i.e. 500:7500, but if a fluid particle leaves the simulation I will now have to alter the range, 500:7499 etc.

Kind regards

**Comment by jmdalonso** [comment]
Hi,
It is not necessary to use a hexadecimal editor to view the contents of bi4 files. The package of the release includes the program ToVTK (src_extra/ToVTK_v5) as an example to read bi4 files and export its data to CSV or VTK files. Remember that the bi4 format is implemented in JPartDataBi4.cpp/h and JBinaryData.cpp/h

The values CaseNp, CaseNfixed are numbers from the original case file since they are useful for filtering by Idp. These values belong to the header fo the bi4 files and are the same in all PART_XXXX.bi4. The bi4 files include other values that change with each PART such as the time or the current number of particles in the simulation.

Anyway, the next update of the release (next week) will include a new post-processing tool to create a XML file with the values in binary files (bi4, ibi4, fbi4...).

**Comment by AhmedSalih3d** [comment]
Thanks for the clarification! I struggled a bit at the time with understanding src_extra, so I have just written my own  library; https://github.com/AhmedSalih3d/PostSPH.jl 

Not release ready, but helps me out in my own research, since it allows me  to read the files quite fast and even save as vtp if I want. Lets me do math easier than Paraview too..

It makes sense with the filtering w.r.t. Idp, I did not consider that initially. I realized after writing my issue that a variable, "Npok" held the actual number of particles in the .bi4. Then by realizing that fluid particles are always placed at the end of the data array (PLEASE correct me if I am wrong), then I could change their "move" value to the length from "begin" to "end-of-array-position". 

Looking forward to the release!

Kind regards

**Comment by jmdalonso** [comment]
Fixed and moving particles are stored at the beginning. Floating and fluid particles are stored at the end, but they are mixed. However this order may change in future versions.

Best regards

**Comment by AhmedSalih3d** [comment]
Thanks for the information! I hope you will be able to "fixate" the positions, it makes it easier to write post-processing scripts. Of course do what makes most sense for DualSPHysics in the end

I have closed the issue, since my misunderstanding was resolved

Kind regards, Ahmed
