### ISSUE TITLE
Some questions about DualSPHysics (DEM)

### ISSUE THREAD

**Issue by LJM-97** [DualSPHysics/DualSPHysics#81]
The attached WORD document is the description of the problem, and the compressed file is the related cases.

I am a beginner of this software ,so some questions will be found in my future exploration.

Thank you for your reading and look forward to your reply.

[Questions.docx](https://github.com/DualSPHysics/DualSPHysics/files/6452010/Questions.docx)
[Dambreak_M02.zip](https://github.com/DualSPHysics/DualSPHysics/files/6452006/Dambreak_M02.zip)
[DEM_M03.zip](https://github.com/DualSPHysics/DualSPHysics/files/6452009/DEM_M03.zip)

**Comment by eleclizard** [comment]
Hi,

Question 1 - The New Dambreak Case
I have read your questions and your input xml file, seems like the simulation is running how you set it out to be. The only thing that you forgot to do is add in the batch command to export the floating bodies. If you go in "wCaseDambreak_win64_GPU.bat" at line 57 (Use Notepad++ to edit that .bat file) you can see that PartVTK is being used to export "PartFluid". You should do the same for "PartBox" by exporting only floating particles. Bellow I have attached the folder with the edit in "wCaseDambreak_win64_GPU.bat".

[Dambreak_M02.zip](https://github.com/DualSPHysics/DualSPHysics/files/6457663/Dambreak_M02.zip)

Question 2 - DEM Case
2-1 The seperation for somewhat a dp length is pretty much a feature from the interaction of the Distributed Contact DEM in DualSPHysics. The only real way to "fix" this is to reduce the dp.
2-2 and 2-3 So I was the user who made that thread about a year ago. Since then I had a close look at the source code of DualSPHysics since the contact (interaction) force between two DEM particles in your floating body is usually a lot higher than the fluid interaction force, the variable timestep calculated by the code is very small than with only fluid. When this happen, the DtMin value acts as an absolute lower limit. Everytime DtVariable < DtMin the code will force the timestep to DtMin. For DEM if your timestep is not small enough to resolve the contact, particle overlap can be too high leading to your DEM particles keep accumulating force and momentum. Eventually, the code will detect that your particle is having a velocity too high, exclude them and eventually terminate the code if too many particles are exceeding the velocity limit. So when you decrease DtMin, the effective timestep can be lower and your result is more physical.

From my experience using DEM in DualSPHyics, the timestep you need to run the code is often is much lower than DtMin and it can take a lot of time to run the simulation. This is probably why DualSPHysics is switching to Chrono with the contact dictated by Differential Variational Inequity method which allows you to have larger timestep. So you should consider switching to Chrono coupling in DualSPHysics

2-4 I actually used stainless steel density of 8000 kg/m3 and it worked fine so I don't think there is a problem.

2-5 You can see from the script that the option is "default". Default hear means that when your domain is generated DualSPHysics will automatically "hug" the true domain based on the max and min X Y Z positions of your particle. You can edit that by putting in your own limits that you desire. But I recommend putting the limit as close to your domain as possible because making the domain too large will slow down your cell searching process for no good reason

**Comment by LJM-97** [comment]
Hi, 

Thank you for your careful explanation. I have also read your reply on the website. There are still a few questions for you to answer.

 (1) Is there any solution to the problem that the fluid has not yet contacted the block(floating) and the block has already started to move? What caused this?(Here is related case: DEM_M05_initial)

(2) “The seperation for somewhat a dp length is pretty much a feature from the interaction of the Distributed Contact DEM in DualSPHysics.” Why is there only one DP between the bottom of the tank and the block in DEM/CaseSolids_Def.xml, but the same operation is not applied between the blocks? The other question is, should the surface of solid contact with solid be separated by a DP distance in DCDEM?

(3) In the previous stage, I simulated a case of fluid impact on a floating body, however when I just readjusted the initial position of the floating body, the program issued a warning, is it because different positions also lead to smaller time-step?(Here are two related cases :   DEM_M05_initial , DEM_M05_readjusted)

(4) The value of the sound speed is usually 10 (gd)½, but why in some seemingly ordinary cases, the value of it is 20 (gd)½or 30 (gd)½? 

Thank you for your reading and look forward to your reply! 

Regards

[DEM_M05_readjusted.zip](https://github.com/DualSPHysics/DualSPHysics/files/6463097/DEM_M05_readjusted.zip)
[DEM_M05_initial.zip](https://github.com/DualSPHysics/DualSPHysics/files/6463106/DEM_M05_initial.zip)

**Comment by eleclizard** [comment]
So I ran your case in DEM_M05_initial and I cannot see any floating body as the output. Did you check the result of GenCase. For (4), the old literature usually have the factor to be 10 but you can always increase it to potentially gain more stability (the variable timestep is reduced).

**Comment by LJM-97** [comment]
Hi,


Sorry that there are some problems with the uploaded cases. But those cases are not the point. I can show the first problem mentioned in my last letter through the following case(DEM_M12). It can be observed that the blocks have moved up and down before the wave interact with them.


In addition, I am puzzled by the second and third questions mentioned in my last letter.


For the third problem, this situation does not only happen when the position of the small object is changed, but also when the accuracy of a case is adjusted, the system will prompt an error. For example, in the following case&nbsp; I provided, only several operations are performed: adjust DP from 0.01 to 0.006, <move x=0 y=0 z=0.006&gt;, adjust the value of CoefDtMin from 0,05 to 0.01. It can run normally without adjusting the precision.


Finally, the materials of the above case follows the settings in DEM / CaseSolids, but when I adjust the materials&nbsp;to following settings, it prompt an error. Should I continue to reduce the value of CoefDtmin?
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <floatings&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; <floating mkbound="60-65" relativeweight="2.715" property="lime-stone" /&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; </floatings&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; <properties&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; <propertyfile file="Floating_Materials.xml" path="materials" /&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; <links&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; <link mkbound="0" property="lime-stone" comment="Property for the tank" /&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; </links&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; </properties&gt;


Regards



------------------ 原始邮件 ------------------
发件人:                                                                                                                        "DualSPHysics/DualSPHysics"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月17日(星期一) 下午4:50
***@***.***&gt;;
抄送:&nbsp;"💪 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [DualSPHysics/DualSPHysics] Some questions about DualSPHysics (DEM) (#81)





 
So I ran your case in DEM_M05_initial and I cannot see any floating body as the output. Did you check the result of GenCase. For (4), the old literature usually have the factor to be 10 but you can always increase it to potentially gain more stability (the variable timestep is reduced).

**Comment by eleclizard** [comment]
I'm not an expert for DualSPHysics distributed contact DEM so I really don't know why these issues are present. There is no good detailed analysis yet for this in the literature and it is pretty much abandoned for DualSPHysics. The development is shifted to Chrono DVI only at the moment I think. Good luck.

**Comment by eleclizard** [comment]
No worries. I'm glad to help. Thanks for the offer!
